name: example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  storage_database:
    path: ../
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  file_picker: ^8.0.3
  pusher_client_fixed: ^0.0.4
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
